### ISSUE TITLE
panic - interface conversion

### ISSUE THREAD

**Issue by aravindkandalam** [JamesWoolfenden/sato#7]
**Describe the bug**
Tried to convert an ARM Template and received the following stack trace.

`
panic: interface conversion: interface {} is map[string]interface {}, not string
goroutine 1 [running]:
sato/src/arm.preprocess(0x10506d8e0?)
	/home/runner/work/sato/sato/src/arm/parse.go:570 +0x500
sato/src/arm.Parse({0x16b59b7b9?, 0x104f8db20?}, {0x16b59b7ca, 0x21})
	/home/runner/work/sato/sato/src/arm/parse.go:79 +0x970
main.main.func3(0x14000178420)
	/home/runner/work/sato/sato/main.go:66 +0x34
github.com/urfave/cli/v2.(*Command).Run(0x14000178420, 0x14000130640, {0x1400015c320, 0x5, 0x5})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/command.go:274 +0x78c
github.com/urfave/cli/v2.(*Command).Run(0x14000178840, 0x14000130500, {0x1400012e120, 0x6, 0x6})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/command.go:267 +0x9ac
github.com/urfave/cli/v2.(*App).RunContext(0x140001cc000, {0x105463ab8?, 0x1400011c588}, {0x1400012e120, 0x6, 0x6})
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/app.go:332 +0x604
github.com/urfave/cli/v2.(*App).Run(...)
	/home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.25.3/app.go:309
main.main()
	/home/runner/work/sato/sato/main.go:116 +0xe38
`

**To Reproduce**

wget https://github.com/JamesWoolfenden/sato/releases/download/v0.1.1/sato_0.1.1_darwin_arm64.tar.gz
tar xzf sato_0.1.1_darwin_arm64.tar.gz
./sato bisect -f template.json -d /Users/xx/AK/GIT/tf1

**Expected behavior**
Converting the ARM Template into TF.

**Screenshots**

**Desktop (please complete the following information):**
- OS: [MacOS 13.4.1 (22F82)]
- Version [0.1.1]
- M2 ARM

**Comment by JamesWoolfenden** [comment]
if you can point me to the arm template sample that causes this thanks

**Comment by aravindkandalam** [comment]
@JamesWoolfenden Can I provide this template in a secure manner?

**Comment by JamesWoolfenden** [comment]
happy to use any method you choose

**Comment by aravindkandalam** [comment]
@JamesWoolfenden https://dl.dataiku.com/file/X8r6PBJHhw12tono/BM7Rxl6YxkKJa193/msftupload.json

**Comment by JamesWoolfenden** [comment]
fixed in v0.1.15
